CREATE TABLE `posts` (
    `id` INT(11) NOT NULL AUTO_INCREMENT,
    `id_user` INT(11) NOT NULL,
    `title` VARCHAR(254) NOT NULL,
    `content` TEXT NOT NULL,
    PRIMARY KEY (`id`),
    FOREIGN KEY (`id_user`)
        REFERENCES users (`id`)
        ON DELETE CASCADE ON UPDATE NO ACTION
)  ENGINE=MyISAM DEFAULT CHARSET=LATIN1;
